logging:
  level:
    .: INFO
    org.springframework: INFO

subsystem1.api:
  domain: "http://localhost"
  port: 8081
  endpoint: "/api/concept1"

---

spring:
  profiles: production

subsystem1.api:
  domain: "https://subdomain.corp.com"
  port: 10081
  endpoint: "/api/concept1"
